source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef-rewind'

group :test do
  gem 'chef', '~> 11.4.0'
  gem 'rspec'
  gem 'chefspec'
  gem 'guard'
  gem 'guard-rspec'
end

group :integration do
  gem 'test-kitchen', '~> 1.0.0.beta'
  gem 'kitchen-vagrant'
end
